const object = properties => ({ type: 'object', properties, required: Object.keys(properties), additionalProperties: false });
const revision = { type: 'integer', description: 'The revision returned by read_site_css or the latest successful edit.' };

export const themeTools = [
  { type: 'function', name: 'read_site_css', description: 'Read the complete current site CSS, including fonts, colors, layout, responsive rules, and the speaking bubble. Returns a revision and the original file path. Read before editing.', strict: true, parameters: object({}) },
  { type: 'function', name: 'edit_site_css', description: 'Edit any part of the CSS using exact find/replace changes. Each find must match exactly once. All edits apply together. Use for fast theme changes, including fonts, @import, @font-face, colors, spacing, layout, and animation. Changes last until refresh or reset.', strict: true, parameters: object({ revision, edits: { type: 'array', minItems: 1, maxItems: 50, items: object({ find: { type: 'string' }, replace: { type: 'string' } }) } }) },
  { type: 'function', name: 'replace_site_css', description: 'Replace the entire active site stylesheet with complete CSS. All selectors are editable, not just theme variables. Preserve usable Chat, Voice, navigation and drawing controls. Changes last until refresh or reset.', strict: true, parameters: object({ revision, css: { type: 'string' } }) },
  { type: 'function', name: 'take_screenshot', description: 'Capture the current page as an image to inspect its theme, fonts, layout, and drawing. Returns the actual rendered DOM as an image to the model; the raw API inspector is omitted. Use after theme edits and fix visible problems before confirming.', strict: true, parameters: object({}) },
  { type: 'function', name: 'reset_site_css', description: 'Discard all theme changes and restore the original public/site.css, including fonts and layout. Keeps the drawing and conversation. Use when asked to reset the theme or recover from a broken appearance.', strict: true, parameters: object({}) },
];
